# Generated by Django 6.0.4 on 2026-04-26 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('locacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='locacao.locacao')),
            ],
        ),
    ]
