# Generated by Django 6.0.4 on 2026-04-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemlocacao', '0003_itemlocacao_preco_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlocacao',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
