# Generated by Django 6.0.4 on 2026-04-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='nome',
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('cadeira', 'Cadeira'), ('mesa', 'Mesa'), ('pula_pula', 'Pula Pula'), ('piscina_bolinha', 'Piscina de Bolinha')], max_length=20),
        ),
    ]
