# Generated by Django 6.0.4 on 2026-04-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_item_nome_alter_item_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('cadeira', 'Cadeira'), ('mesa', 'Mesa'), ('pula_pula-pequeno', 'Pula Pula-pequeno'), ('piscina_bolinha', 'Piscina de Bolinha'), ('pula_pula-grande', 'Pula Pula-grande')], max_length=20),
        ),
    ]
