# Generated by Django 6.0.4 on 2026-04-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_nome_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('nome', 'telefone'), name='unique_cliente_nome_telefone'),
        ),
    ]
