# Generated by Django 6.0.4 on 2026-05-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_unique_cliente_nome_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
