# Generated by Django 6.0.4 on 2026-05-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
