# Generated by Django 6.0.4 on 2026-04-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada')], default='ativa', max_length=20),
        ),
    ]
