# Generated by Django 6.0.4 on 2026-04-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0002_locacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
