# Generated by Django 6.0.4 on 2026-04-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0003_alter_locacao_preco_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='endereco_bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='endereco_referencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='endereco_rua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
