# Generated by Django 6.0.4 on 2026-05-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0004_locacao_endereco_bairro_locacao_endereco_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
