# Generated by Django 6.0.4 on 2026-05-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0005_alter_locacao_preco_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='preco_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
