# Generated by Django 6.0.4 on 2026-05-13 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combo', '0001_initial'),
        ('locacao', '0005_alter_locacao_preco_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combo.combo')),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='locacao.locacao')),
            ],
        ),
    ]
